### ISSUE TITLE
Have image on home page move up when scrolling into that section.

### ISSUE THREAD

**Issue by tobijah** [Spbaciuc/marketdd#5]

**Comment by tobijah** [comment]
Change to Fade in from Bottom as seen on this website: https://www.sitepoint.com/scroll-based-animations-jquery-css3/

**Comment by Spbaciuc** [comment]
what is     margin: 0% 1.33 2.66% 1.33%; for?

**Comment by tobijah** [comment]
Oops sorry I didn't see that you asked. Margin adds space around the box you are working with. You can add it as a pixel or if you want it to change based on the user's screen size you can do it in percent. It will find the 100% width of the area then add 0% space to the top, 1.33% to the right, 2.66% space to the bottom and 1.33% to the left.

**Comment by Spbaciuc** [comment]
hmm should i use index.php as html?

**Comment by tobijah** [comment]
It is actually page-home.php

**Comment by Spbaciuc** [comment]
i will check and put code line in right line

**Comment by tobijah** [comment]
Awesome the image you are looking for has the class name home-img on line 36

**Comment by Spbaciuc** [comment]
yes, that is why I tried to type "," to add animation element tag.

**Comment by tobijah** [comment]
Sweet can you sync it up so I can take a look?

**Comment by Spbaciuc** [comment]
go ahead

**Comment by tobijah** [comment]
I added a commit with a message. By the way, you were right. It is supposed to be index.php

**Comment by Spbaciuc** [comment]
I have question. which order i should put: <php> <tag> </> </> or <tag><php></></>?

**Comment by Spbaciuc** [comment]
oh it was gone

**Comment by tobijah** [comment]
Hmmm... looks like the same order for me

**Comment by tobijah** [comment]
I did find what was causing it not to work

**Comment by tobijah** [comment]
I synced the fix

**Comment by Spbaciuc** [comment]
I can't submit latest line

**Comment by tobijah** [comment]
What error is it showing you? You can take a screenshot and post it on here

**Comment by Spbaciuc** [comment]
I will put it this tag inside php to add div class=animation element.

**Comment by Spbaciuc** [comment]
OK it is fixed
