### ISSUE TITLE
Next week: Add Visual Composer to theme

### ISSUE THREAD

**Issue by tobijah** [Spbaciuc/marketdd#8]
Every theme now on themeforest comes with this plugin so we will have to add it. You can learn about it here: https://vc.wpbakery.com/

**Comment by Spbaciuc** [comment]
should i sign up this? https://vc.wpbakery.com/try/

**Comment by tobijah** [comment]
I just uploaded the plugin. So you can sync it up. a13ef656a810823d7ded5a8091ee0386a8a2061a

**Comment by Spbaciuc** [comment]
thank you.
